### ISSUE TITLE
Add to status API value of VPN IP address

### ISSUE THREAD

**Issue by bclermont** [UnblockApp/unblockapp-win-demo#4]
Is it possible to add to

https://github.com/UnblockApp/unblockapp-win-demo#get-status

response an additional key that is the actual VPN address assigned by VPN server, such as ``172.16.0.2`` with freevpn?

**Comment by bclermont** [comment]
if that is possible, we can have software that only bind to the address of the VPN, which make that a lot more easier to restrict traffic to VPN only.

please let me know if that is possible

**Comment by bclermont** [comment]
in private @mogikanin confirmed it's possibe, convert it to task

**Comment by mogikanin** [comment]
Moved to https://github.com/UnblockApp/unblockapp-win/issues/23
