### ISSUE TITLE
need confirmation on how built file work

### ISSUE THREAD

**Issue by hvnsweeting** [UnblockApp/unblockapp-win-demo#5]
Hello, I've built this project and with the output in ``UnblockAppDemoApp\bin\Debug\``, I can run the .exe file when ``.exe.config`` file exists. If I remove ``.exe.config`` file, running ``.exe`` file will just show nothing(maybe it ran then crashed?)

So I need your input to confirm that it needs 2 files after build the software to work or just .exe file?

Thanks,

**Comment by mogikanin** [comment]
Yes, .config file also needed.
